#!/usr/bin/env bash
# This script installs and configures nginx on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow'NginxHTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
