#!/usr/bin/env bash
# Install nginx on web-01

# Updating packages and installing nginX
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Create HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html
