#!/usr/bin/env bash
# Installing nginx on default port using apt-get

# Installation of nginx using the get
sudo apt-get update -y
sudo apt-get install nginx -y

# Set file paths
ERROR_404_FILE="/var/www/html/page_404.html"
NGINX_CONF="/etc/nginx/sites-available/default"
FILE_PATH="/var/www/html/index.html"


# Creating an index file that displays 'Hello World!'
sudo bash -c "echo 'Hello World!' > $FILE_PATH"


# Setting write authorization procedure
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


# Setting up / redirect to a youtube video
sudo sed -i '/server_name _;/a\         rewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' "$NGINX_CONF"


# Setting up a custom 404 page
echo "Ceci n'est pas une page" > "$ERROR_404_FILE"
sudo sed -i '/server_name _;/a\       error_page 404 /page_404.html;' $NGINX_CONF


# Restarting nginx
sudo service nginx restart
