#!/usr/bin/env bash
# change the user to nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# change the port 80 to listen to port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
#change permission which common among configuration files
chmod 644 /etc/nginx/nginx.conf
# avoid Port Conflict
pkill apache2
# start service as nginx user
sudo -u nginx service nginx start
